version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: androidx.fragment:fragment-ktx
    versions:
    - 1.3.0
    - 1.3.1
    - 1.3.2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.vanniktech:gradle-maven-publish-plugin
    versions:
    - 0.13.0
    - 0.14.0
    - 0.14.1
    - 0.14.2
  - dependency-name: androidx.lifecycle:lifecycle-livedata-core-ktx
    versions:
    - 2.3.0
  - dependency-name: androidx.lifecycle:lifecycle-common-java8
    versions:
    - 2.3.0
