name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Install Android SDK
        run: ./.github/android-sdk.sh

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build docs
        run: ./gradlew dokkaGfm

      - name: Copy docs
        run: |
          cp README.md docs/index.md
          mkdir -p docs/Javadoc/connect-flow
          cp -R connect-flow/build/dokka/gfm/. docs/Javadoc/connect-flow/
          mkdir -p docs/Javadoc/connect-flow
          cp -R connect-flow-rx/build/dokka/gfm/. docs/Javadoc/connect-flow-rx/
          mkdir -p docs/Javadoc/connect-livedata
          cp -R connect-livedata/build/dokka/gfm/. docs/Javadoc/connect-livedata/
          mkdir -p docs/Javadoc/connect-livedata
          cp -R connect-livedata-rx/build/dokka/gfm/. docs/Javadoc/connect-livedata-rx/
          mkdir -p docs/Javadoc/renderer
          cp -R renderer/build/dokka/gfm/. docs/Javadoc/renderer/
          mkdir -p docs/Javadoc/renderer-list
          cp -R renderer-list/build/dokka/gfm/. docs/Javadoc/renderer-list/

      - name: Deploy MkDocs
        run: |
          git fetch origin gh-pages:gh-pages
          mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
